export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPINGINFO = 'CART_SAVE_SHIPPINGINFO';
export const CART_SAVE_PAYMENTINFO = 'CART_SAVE_PAYMENTINFO';
export const CART_EMPTY = 'CART_EMPTY';